### Домашнее задание «Библиотека numpy. Вычислительные задачи»

#### Задание 1

Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [1]:
import numpy as np

In [34]:
def np_array_reverse(N):
    np_array = np.arange(0, N)
    return np.flip(np_array, axis=None)

np_array_reverse(10)

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

#### Задание 2

Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [53]:
diag_np = np.diag(np_array_reverse(10))
print(diag_np)
print(f'\nСумма элементов по диагонали: {sum(diag_np.diagonal())}')

[[9 0 0 0 0 0 0 0 0 0]
 [0 8 0 0 0 0 0 0 0 0]
 [0 0 7 0 0 0 0 0 0 0]
 [0 0 0 6 0 0 0 0 0 0]
 [0 0 0 0 5 0 0 0 0 0]
 [0 0 0 0 0 4 0 0 0 0]
 [0 0 0 0 0 0 3 0 0 0]
 [0 0 0 0 0 0 0 2 0 0]
 [0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0]]

Сумма элементов по диагонали: 45


#### Задание 3
Решите систему уравнений:  
4x + 2y + z = 4  
x + 3y = 12  
5y + 4z = -3  

In [72]:
"""
4x + 2y + 1z = 4
1x + 3y + 0z = 12
0x + 5y + 4z = -3
"""

matrix_np = np.array([[4, 2, 1], [1, 3, 0], [0, 5, 4]])
vector_np = np.array([4, 12, -3])

np.linalg.solve(matrix_np, vector_np)

array([ 0.46666667,  3.84444444, -5.55555556])

#### Задание 4

Имеется матрица покупок в интернет-магазине. Столбец А - ID пользователя. Остальные столбцы - количество покупок категорий товаров этим пользователем:  
На сайт заходит очередной посетитель, о покупках которого известно следующее:  
next_user_stats = np.array([0, 1, 2, 0, 0, 0])  
Найдите самого похожего пользователя. Т. е. посчитайте косинусное сходство между этим пользователем и всеми пользователями из массива user_stats

In [74]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

next_user_stats = np.array([0, 1, 2, 0, 0, 0])

In [93]:
def cosine(a, b):
    aLength = np.linalg.norm(a)
    bLength = np.linalg.norm(b)
    return np.dot(a, b) / (aLength * bLength)

In [94]:
def find_most_similar_user(matrix, vector):
    max_cosine = [0, 0]
    for number, row in enumerate(matrix):
        if cosine(row, vector) > max_cosine[1]:
            max_cosine = [number, cosine(row, vector)]
    return f'User ID: {max_cosine[0]+1}, Cosine: {max_cosine[1]}'

In [95]:
find_most_similar_user(users_stats, next_user_stats)

'User ID: 8, Cosine: 0.9486832980505138'